### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by mikolajkalwa** [kowalskiwiktor98/windows-terminal-context-menu#1]
Hey
I've just used the attached reg file, and I'm getting the following error when I choose Open Windows Terminal here from context menu: 
![nie dziala](https://user-images.githubusercontent.com/13047857/88468491-ecdd1a80-cee4-11ea-8238-0164beef8cc0.png)

**Comment by mikolajkalwa** [comment]
It says:
unable to find application

**Comment by mikolajkalwa** [comment]
pls fix asap

**Comment by kowalskiwiktor98** [comment]
Fixed, thanks for catching that mistake
